/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	// docsSidebar: [{ type: 'autogenerated', dirName: '.' }],

	// But you can create a sidebar manually
	docsSidebar: [
		{
			type: 'doc',
			id: 'getting-started',
			label: 'Getting started',
		},
		{
			type: 'category',
			label: 'Tutorial',
			items: ['Tutorial/quick-start'],
		},
		{
			type: 'category',
			label: 'Examples',
			items: [
				'Examples/01-static-map-with-one-marker',
				'Examples/02-interactive-map',
				'Examples/03-interactive-map-with-layout-switcher',
				'Examples/04-interactive-map-multiple-markers',
				'Examples/05-interactive-map-with-thousands-of-points',
				'Examples/06-interactive-map-with-thousands-of-points-marker',
				'Examples/07-interactive-map-with-clusters-and-signals',
				'Examples/08-interactive-map-with-search',
				'Examples/09-interactive-map-with-pointer',
				'Examples/10-interactive-map-with-route',
				'Examples/11-static-map-with-marker-and-card',
			],
		},
		{
			type: 'category',
			label: 'API',
			items: [
				'API/clusterer',
				'API/keyboard-control',
				'API/layer-control',
				'API/map',
				'API/map-provider',
				'API/marker',
				'API/marker-layer',
				'API/mouse-control',
				'API/multiple-markers',
				'API/pointer',
				'API/route',
				'API/route-layer',
				'API/search-input',
				'API/signals',
				'API/sync-control',
				'API/zoom-control',
			],
		},
	],
};
